### PR TITLE
Removing PyPlot dependency

### PR DESCRIPTION
**Pull request by nlw0**
This PR removes PyPlot from the dependencies, and straight up comments all functions where it is used. I believe it may be possible to make a nicer change, though. Pkg now supports targets, maybe we could create a "demo" target or something similar? Please let me know how else we could restructure things.

### CODE REVIEW

**Comment by PaulDebus** [comment]
I would support removing the PyPlot dependency, GitHub Action testing does not like it. I replaced the PyPlot implementation with a GLMakie one in a recent project and could provide that code. It would require swapping the rendering, however.

Targets could be an option to include conditional dependencies, I do not know enough about that though...

**Comment by peterkovesi** [comment]
@nlw0 @PaulDebus  Sorry for the silence, I have been mulling over things.  I developed this code some time ago (starting perhaps 20 years ago, originally in MATLAB).  However I am now retired and have not used the code for several years and do not anticipate I will ever use it again.  Given this I feel it is not appropriate that I should be managing PRs, and deciding how this code should be developed and taken forwards as I will never use it.  Would either of you be interested in taking on (perhaps joint) ownership of this package?

**Comment by PaulDebus** [comment]
I think retirement is a very fine reason to not answer instantly ;) And also for taking a step back from active development. 

Currently, I am using the library quite frequently for my PhD, so I would be open to contributing as a maintainer, happily in a team with @nlw0. I have some ideas on how to develop the package, that are around my research topics, but am also interested in bringing this package and the Julia ecosystem around image processing forward.

**Comment by nlw0** [comment]
Sure @peterkovesi, I find the package pretty useful. I'd probably start going straight ahead and removing the plotting code, though, that we can later find another home to, because it really makes the difference for having the package as a dependency in other projects. Then me and @PaulDebus can review each other's PRs!

**Comment by PaulDebus** [comment]
Hello,

sounds fine to me so far, though I would hope to bring the code back in an improved way rather soon. Maybe we con use something like [weak dependencies and extensions](https://pkgdocs.julialang.org/v1/creating-packages/#Weak-dependencies) for that - which would require Julia 1.9 to work well. But this is probably a discussion for a new issue/PR

Best, Paul

**Comment by PaulDebus** [comment]
There are two different errors in the CI.

1. Julia LTS (1.4) fails because it does not know about extensions. I naively thought it would be kind of backward compatible, but it apparently is not... I will look into this
2. The `derivatives3` function is not found in testing (as is also the case with PR #37) which I do not really understand - *works on my machine*. Will also take another look

**Pull request merged**
